website/auth.py
import os
import re
from pymongo import MongoClient
from flask_login import LoginManager, UserMixin, login_user, logout_user
from flask_mail import Mail, Message
from dotenv import load_dotenv, find_dotenv
from itsdangerous import URLSafeTimedSerializer
from email_validator import validate_email, EmailNotValidError
from werkzeug.security import check_password_hash, generate_password_hash
from flask import Blueprint, url_for, redirect, flash, request, render_template, session, current_app
from . import mail
from flask import current_app as app

load_dotenv(find_dotenv())

PASSWORD = os.environ.get("MONGODB_PWD")

auth = Blueprint('auth', __name__)

password = os.environ.get("MONGODB_PWD")
connection = f"mongodb+srv://toby:{PASSWORD}@wayabroad.ytg2mkg.mongodb.net/?retryWrites=true&w=majority&appName=wayabroad"

client = MongoClient(connection)
db = client['userDB'] 
collection = db['users'] 

class User(UserMixin):
    def __init__(self, data):
        self.id = data["_id"]
        self.password = data["password"]

    @staticmethod
    def get(user_id):
        data = collection.find_one({"_id": user_id})
        if data:
            return User(data)
        return None

    def get_reset_token(self, expires_sec=1800):
        s = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        return s.dumps(self.id, salt='sweetbananas')  # Change this line

    @staticmethod
    def verify_reset_token(token):
        s = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token, salt='sweetbananas', max_age=1800)  # Change this line
        except SignatureExpired:
            return None  # valid token, but expired
        except BadTimeSignature:
            return None  # invalid token
        user = User.get(user_id)
        return user

@auth.route('/register', methods=['GET'])
def register():
    return render_template('register.html')

@auth.route('/register', methods=['POST'])
def signup():
    # Get the user's information from the request
    fullname = request.form.get('fullname')
    email = request.form.get('email')
    password = request.form.get('password')
    find_us_options = request.form.get('findUsOptions')

    # Validate email
    try:
        v = validate_email(email)  # validate and get info
        email = v["email"]  # replace with normalized form
    except EmailNotValidError as e:
        # email is not valid, handle exception
        flash('Please provide a valid email address.', 'danger')
        return redirect(url_for('auth.register'))

    # Validate password
    password_regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$"
    if not re.match(password_regex, password):
        flash('Password must contain at least one uppercase letter, one lowercase letter, one number, and be at least 8 characters long.', 'warning')
        return redirect(url_for('auth.register'))

    # Check if a user with the given email already exists
    user = collection.find_one({"email": email})

    if user:  # if a user is found, we want to redirect back to signup page so user can try again
        flash('Email address already exists', 'danger')
        return redirect(url_for('auth.register'))

    # Hash the password before storing it
    password_hash = generate_password_hash(password, method='pbkdf2:sha256')

    # Store the data in MongoDB
    user_data = {
        "_id": email, 
        "fullname": fullname,
        "email": email,
        "password": password_hash,
        "find_us_options": find_us_options,
    }
    collection.insert_one(user_data)

    session['user'] = email  # set the session variable

    user = User(user_data)  # create a User object
    login_user(user)  # log in the user

    flash(f'Welcome to our website {fullname}!', 'success')
    return render_template('register.html', user_created=True)

@auth.route('/login', methods=['GET'])
def login():
    return render_template('login.html')

@auth.route('/login', methods=['POST'])
def signin():
    email = request.form.get('email')
    password = request.form.get('password')

    # Validate email
    try:
        v = validate_email(email)  # validate and get info
        email = v["email"]  # replace with normalized form
    except EmailNotValidError as e:
        # email is not valid, handle exception
        flash('Please provide a valid email address.', 'danger')
        return redirect(url_for('auth.login'))

    # Validate password
    if not password:
        flash('Please provide a password.', 'danger')
        return redirect(url_for('auth.login'))

    # Check if the user exists in the database
    user = User.get(email)
    if user and check_password_hash(user.password, password):
        login_user(user)  # log in the user
        flash('Successfully logged in!', 'success')
        return render_template("login.html", user_created=True)

    flash('Please check your login details and try again.', 'danger')
    return redirect(url_for('auth.login'))  # if user doesn't exist or password is wrong, reload the page

@auth.route('/logout')
def logout():
    logout_user()
    #flash('You have been logged out.', 'success')
    return redirect(url_for('views.home'))

@auth.route('/forgot-password')
def forgot_password():
    return render_template('forgot-password.html')

@auth.route('/reset-password/', methods=['GET', 'POST'])
def reset_password():
    return render_template('reset-password.html')

@auth.route('/forgot-password', methods=['POST'])
def send_reset_email():
    email = request.form.get('email')

    # Validate email
    try:
        v = validate_email(email)  # validate and get info
        email = v["email"]  # replace with normalized form
    except EmailNotValidError as e:
        # email is not valid, handle exception
        flash('Please provide a valid email address.', 'danger')
        return redirect(url_for('auth.forgot_password'))

    # Check if the user exists in the database
    user = User.get(email)
    if user:
        # Generate a reset token
        token = user.get_reset_token()

        # Generate the reset password link with the token as a query parameter
        reset_link = url_for('auth.reset_password_token', token=token, _external=True)

        # Send an email to the user with the reset link
        msg = Message('Password Reset Request',
                      sender='noreply@demo.com',
                      recipients=[user.id])
        msg.body = f'''To reset your password, visit the following link:
{reset_link}

If you did not make this request then simply ignore this email and no changes will be made.
'''
        mail.send(msg)

        flash('An email has been sent with instructions to reset your password.', 'info')
    else:
        flash('No account found with that email.', 'warning')

    return redirect(url_for('auth.forgot_password'))

@auth.route('/new-password/', methods=['GET', 'POST'])
def reset_password_token():
    token = request.args.get('token')
    if not token:
        flash('Invalid token', 'danger')
        return redirect(url_for('auth.forgot_password'))

    user = User.verify_reset_token(token)
    if not user:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('auth.forgot_password'))

    if request.method == 'POST':
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')

        if password != confirm_password:
            flash('Passwords do not match.', 'warning')
            return redirect(url_for('auth.reset_password'))

        password_regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$"
        if not re.match(password_regex, password):
            flash('Password must contain at least one uppercase letter, one lowercase letter, one number, and be at least 8 characters long.', 'warning')
            return redirect(url_for('auth.reset_password'))

        password_hash = generate_password_hash(password, method='pbkdf2:sha256')
        collection.update_one({"_id": user.id}, {"$set": {"password": password_hash}})
        logout_user()
        flash('Your password has been updated! Please login again', 'success')
        return redirect(url_for('auth.login'))

    return render_template('reset-password.html', token=token)

website/views.py
from bson.json_util import dumps
from flask import Flask, Blueprint, render_template, jsonify
from pymongo import MongoClient
import os
from flask import request
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())

PASSWORD = os.environ.get("MONGODB_PWD")
connection = f"mongodb+srv://toby:{PASSWORD}@wayabroad.ytg2mkg.mongodb.net/?retryWrites=true&w=majority&viewsName=wayabroad"

client = MongoClient(connection)
universitiesDB = client['universityDB']
blogsDB = client['blogsDB']

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template('index.html')

@views.route('/blog')
def blog():
    return render_template('blog.html')

@views.route('/blog/data')
def blog_data():
    blogDB = blogsDB.blogs.find()
    data = [doc for doc in blogDB]
    return dumps(data)

@views.route('/university')
def university():
    return render_template('university.html')

@views.route('/university/data')
def university_data():
    universityDB = universitiesDB.universities.find()  
    data = [doc for doc in universityDB]
    return dumps(data)  # convert data to JSON string

@views.route('/majors/data')
def majors_data():
    majorsDB = universitiesDB.majorsDB.find()  
    data = [doc for doc in majorsDB]
    return dumps(data)  # convert data to JSON string

@views.route('/team')
def team():
    return render_template('team.html')

@views.route('/contact')
def contact():
    return render_template('contact.html')

@views.route('/more-info')
def more_info():
    university_name = request.args.get('university')
    university_data = universitiesDB.universities.find_one({"university_name": university_name})
    return render_template('more-info.html', data=university_data)

website/templates/team.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Our team</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon">
    <link href="{{ url_for('static', filename='img/apple-touch-icon.png') }}" rel="apple-touch-icon">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


    <!-- Vendor CSS Files -->
    <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/aos/aos.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">

    <!-- Main CSS File -->
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
</head>

<body>

    <!-- Responsive navbar-->
    <header id="header" class="header d-flex align-items-center fixed-top">
        <div class="container-fluid container-xl position-relative d-flex align-items-center">

            <a href="{{ url_for('views.home') }}" class="logo d-flex align-items-center me-auto">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <img src="{{ url_for('static', filename='img/logo.png') }}" alt="">
            </a>

            <nav id="navmenu" class="navmenu">
                <ul>
                    <li><a href="{{ url_for('views.home') }}">Home</a></li>
                    <li><a href="{{ url_for('views.blog') }}">Blog</a></li>
                    <li><a href="{{ url_for('views.university') }}">Programs</a></li>
                    <li><a href="{{ url_for('views.team') }}" class="active">Our team</a></li>
                    <li><a href="{{ url_for('views.contact') }}">Contact</a></li>
                </ul>
                <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
            </nav>

           {% if not current_user.is_authenticated %}
           <a class="btn-getstarted" href="{{ url_for('auth.register') }}">Get Started</a>
           {% else %}
           <a class="btn-getstarted" href="{{ url_for('auth.logout') }}">Log Out</a>
           {% endif %}

        </div>
    </header>


    <section class="our-webcoderskull padding-lg vh-100">
        <div class="container">
            <div class="row heading heading-icon">
                <h2>Our Team</h2>
            </div>
            <ul class="row">
                <li class="col-12 col-md-6 col-lg-3">
                    <div class="cnt-block equal-hight" style="height: 349px;">
                        <figure><img src="http://www.webcoderskull.com/img/team4.png" class="img-responsive" alt="">
                        </figure>
                        <h3><a href="http://www.webcoderskull.com/">Web coder skull</a></h3>
                        <p>Freelance Web Developer</p>
                        <ul class="follow-us clearfix">
                            <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </li>
                <li class="col-12 col-md-6 col-lg-3">
                    <div class="cnt-block equal-hight" style="height: 349px;">
                        <figure><img src="http://www.webcoderskull.com/img/team1.png" class="img-responsive" alt="">
                        </figure>
                        <h3><a href="#">Kappua </a></h3>
                        <p>Freelance Web Developer</p>
                        <ul class="follow-us clearfix">
                            <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </li>
                <li class="col-12 col-md-6 col-lg-3">
                    <div class="cnt-block equal-hight" style="height: 349px;">
                        <figure><img src="http://www.webcoderskull.com/img/team4.png" class="img-responsive" alt="">
                        </figure>
                        <h3><a href="http://www.webcoderskull.com/">Manish </a></h3>
                        <p>Freelance Web Developer</p>
                        <ul class="follow-us clearfix">
                            <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </li>
                <li class="col-12 col-md-6 col-lg-3">
                    <div class="cnt-block equal-hight" style="height: 349px;">
                        <figure><img src="http://www.webcoderskull.com/img/team2.png" class="img-responsive" alt="">
                        </figure>
                        <h3><a href="http://www.webcoderskull.com/">Atul </a></h3>
                        <p>Freelance Web Developer</p>
                        <ul class="follow-us clearfix">
                            <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </section>


    <footer id="footer" class="footer">
        <div class="container footer-top">
            <div class="row gy-4">
                <div class="col-lg-6 col-md-6 footer-about">
                    <h4 class="text-uppercase"><span class="sitename">Wayabroad</span></h4>
                    <p>Seoul, South Korea</p>
                    <p><strong>Phone:</strong> +82 10 9575 8404</p>
                    <p><strong>Email:</strong> info@example.com</p>
                </div>

                <div class="col-lg-6 col-md-6">
                    <h4 class="text-uppercase">Follow Us</h4>
                    <p>Stay updated with our latest news and offers. Connect with us on social media.</p>
                    <div class="social-links d-flex">
                        <a href="" class="btn btn-social-icon btn-twitter"><i class="bi bi-telegram"></i></a>
                        <a href="" class="btn btn-social-icon btn-facebook"><i class="bi bi-twitter"></i></a>
                        <a href="" class="btn btn-social-icon btn-instagram"><i class="bi bi-instagram"></i></a>
                        <a href="" class="btn btn-social-icon btn-linkedin"><i class="bi bi-linkedin"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="container copyright text-center mt-4">
            <p>© 2024 <strong class="px-1 sitename">Wayabroad, Inc.</strong></p>
            <div class="credits">
                Made by <a href="https://www.linkedin.com/in/habibullo-chutboev/">Habibullo Dev</a>
            </div>
        </div>
    </footer>
</body>

website/templates/university.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>University Search</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon">
    <link href="{{ url_for('static', filename='img/apple-touch-icon.png') }}" rel="apple-touch-icon">
    
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/aos/aos.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">

    <!-- Main CSS File -->
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
</head>

<body>

    <!-- Responsive navbar-->
    <header id="header" class="header d-flex align-items-center fixed-top">
        <div class="container-fluid container-xl position-relative d-flex align-items-center">

            <a href="{{ url_for('views.home') }}" class="logo d-flex align-items-center me-auto">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <img src="{{ url_for('static', filename='img/logo.png') }}" alt="">
            </a>

            <nav id="navmenu" class="navmenu">
                <ul>
                    <li><a href="{{ url_for('views.home') }}">Home</a></li>
                    <li><a href="{{ url_for('views.blog') }}">Blog</a></li>
                    <li><a href="{{ url_for('views.university') }}" class="active">Programs</a></li>
                    <li><a href="{{ url_for('views.team') }}">Our team</a></li>

                    <li><a href="{{ url_for('views.contact') }}">Contact</a></li>
                </ul>
                <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
            </nav>

           {% if not current_user.is_authenticated %}
           <a class="btn-getstarted" href="{{ url_for('auth.register') }}">Get Started</a>
           {% else %}
           <a class="btn-getstarted" href="{{ url_for('auth.logout') }}">Log Out</a>
           {% endif %}
        </div>
    </header>

    <main class="mt-5 pt-5">
        <div class="container text-center">
            <h2 class="py-3">Keyword Search:</h2>
            <form class="my-4">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search by university name">
                    <button class="btn btn-outline-primary" type="submit">Search</button>
                </div>
            </form>

            <div class="row row-cols-1 row-cols-md-2 g-4 mb-3">
                <!-- Cards will be appended here by JavaScript -->
            </div>
            <button class="btn btn-outline-primary btn-lg my-3 load-more-btn">Load More</button>
        </div>
    </main>

    <!-- Footer -->
    <footer id="footer" class="footer">
        <div class="container footer-top">
            <div class="row gy-4">
                <div class="col-lg-6 col-md-6 footer-about">
                    <h4 class="text-uppercase"><span class="sitename">Wayabroad</span></h4>
                    <p>Seoul, South Korea</p>
                    <p><strong>Phone:</strong> +82 10 9575 8404</p>
                    <p><strong>Email:</strong> info@example.com</p>
                </div>

                <div class="col-lg-6 col-md-6">
                    <h4 class="text-uppercase">Follow Us</h4>
                    <p>Stay updated with our latest news and offers. Connect with us on social media.</p>
                    <div class="social-links d-flex">
                        <a href="" class="btn btn-social-icon btn-twitter"><i class="bi bi-telegram"></i></a>
                        <a href="" class="btn btn-social-icon btn-facebook"><i class="bi bi-twitter"></i></a>
                        <a href="" class="btn btn-social-icon btn-instagram"><i class="bi bi-instagram"></i></a>
                        <a href="" class="btn btn-social-icon btn-linkedin"><i class="bi bi-linkedin"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="container copyright text-center mt-4">
            <p>© 2024 <strong class="px-1 sitename">Wayabroad, Inc.</strong></p>
            <div class="credits">
                Made by <a href="https://www.linkedin.com/in/habibullo-chutboev/">Habibullo Dev</a>
            </div>
        </div>
    </footer>
    <!-- End Footer -->

    <!-- Scroll Top -->
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Preloader -->
    <div id="preloader"></div>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>

    <!-- Vendor JS Files -->
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/aos/aos.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/glightbox/js/glightbox.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/waypoints/noframework.waypoints.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/imagesloaded/imagesloaded.pkgd.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>

    <!-- Main JS File -->
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <script src="{{ url_for('static', filename='js/university.js') }}"></script>
</body>

</html>

website/templates/user-profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>
    <!-- Favicons -->
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon">
    <link href="{{ url_for('static', filename='img/apple-touch-icon.png') }}" rel="apple-touch-icon">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/aos/aos.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">

    <!-- Main CSS File -->
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
</head>

<body>
    <div class="container">
        <div class="row">
            <!-- Left sidebar -->
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Navigation</h5>
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link active" href="#">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Profile</a>
                            </li>
                            <!-- Add more navigation links as needed -->
                        </ul>
                    </div>
                </div>
            </div>
    
            <!-- User profile -->
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ user.fullname }}</h5>
                        <p class="card-text">{{ user.email }}</p>
                        <p class="card-text">Found us through: {{ user.find_us_options }}</p>
                    </div>
                </div>
            </div>
    
            <!-- Right sidebar -->
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Instructions</h5>
                        <p class="card-text">Here you can add instructions or any other information for the user.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main JS file -->
    <script src="{{ url_for('static', filename='js/profile.js') }}"></script>

</body>

</html>